export enum UserRole {
  DEVELOPER = "DEVELOPER",
  L1_APPROVER = "APPROVER_L1",
  L2_APPROVER = "APPROVER_L2",
  L3_APPROVER = "APPROVER_L3",
  L4_APPROVER = "APPROVER_L4",
  DCOPS = "DC_OPS",
  REQUESTER = "REQUESTER",
  ADMIN = "ADMIN",
}

export enum NotificationType {
  APPROVAL_REQUIRED = "APPROVAL_REQUIRED",
  STATUS_UPDATE = "STATUS_UPDATE",
  DIRECTOR_ESCALATION = "DIRECTOR_ESCALATION",
  EXECUTION_READY = "EXECUTION_READY",
  SYSTEM = "SYSTEM",
}
